import React, {useState} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMoralis } from "react-moralis";

import {
  BodyCon, BodyHeaderCon, RandomizingHeader, SubHeader, PeopleBlobs, HomePageButtonConnectWallet, HomePageButtonConnectWalletInvert, 
  
  ProjectCardCon, BodySectionCon, BodySectionHeader, BodySectionDescription, ProjectCardButton, TimelineCon,  BodySectionImageCon
} from "../components/HomePage/HomePageElements"

import ProjectTimelineCardCon from "../components/Projects/ProjectTimelineCard"
import ProjectCard from "../components/Projects/ProjectCard"
import InvestorCard from "../components/Projects/InvestorCard"

import OrangeBlob from "../assets/People/Orange_Blob.png"
import BlueBlob from "../assets/People/Blue_Blob.png"
import PurpleBlob from "../assets/People/Purple_Blob.png"
import DreamerImage from "../assets/SiteElements/dreamerslide.png"
import Will from "../assets/People/memoji-will.png"
import Sergey from "../assets/People/memoji-sergey.png"

const wordArray = [
  'NFT project', 'Hackathon scholarship', 'Trip to ETHDenver', 'recording equipment', 'Guitar lessons', 'Word bank', 'economic justice', 'literacy program', 'Animation', 'Dream journal', 'Dream vaction', 'Dream job', 'Dream life', 'Data pipeline', 'Production guild bounty', 'Medical bills', 'School', 'College Tuition', 'Language lessons'
]

function Home () {
  const { 
    authenticate, 
    isAuthenticated, 
    user,
  } = useMoralis();

  const [randomItem, setRandomItem] = useState('');

  const timoutId = setTimeout(() => {
    var randomItem = wordArray[Math.floor(Math.random() * wordArray.length)];
    setRandomItem(randomItem);
  }, 8000);

  if(!isAuthenticated)
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>GoFundYourself</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <BodyCon>
        <BodyHeaderCon>
          <RandomizingHeader>
            a home for <span style={{fontWeight: "650"}}>anyone</span> to <span style={{fontWeight: "650"}}>fund their <span style={{textDecoration: "underline"}}>{randomItem}</span></span>
          </RandomizingHeader>
          <SubHeader>
            don&apos;t let your <span style={{fontWeight: "650"}}>dreams</span> be <span style={{fontWeight: "650"}}>web3 memes</span>
          </SubHeader>
          <SubHeader style={{
              display: "inline-flex", 
              textAlign: "center",
              left: "50%",
              position: "relative",
              transform: "translate(-50%)",
              marginTop: "50px"
            }}>
            <HomePageButtonConnectWallet onClick={() => authenticate({signingMessage:"Welcome to GoFundYourself! Sign in using Metamask wallet with a gas-less, free transaction to access the dapp."})}>
                get funds
            </HomePageButtonConnectWallet>
            <HomePageButtonConnectWalletInvert onClick={() => authenticate({signingMessage:"Welcome to GoFundYourself! Sign in using Metamask wallet with a gas-less, free transaction to access the dapp."})}>
                go fund
            </HomePageButtonConnectWalletInvert>
          </SubHeader>

          <PeopleBlobs style={{marginBottom: "20px"}}>
            <Image src={OrangeBlob} height="250px" width="250px" alt="Person Blob"/>
            <Image src={BlueBlob} height="250px" width="250px" alt="Person Blob"/>
            <Image src={PurpleBlob} height="250px" width="250px" alt="Person Blob"/>
          </PeopleBlobs>
        </BodyHeaderCon>

        <BodySectionCon>
          <BodySectionHeader>
            are you a dreamer?  
          </BodySectionHeader>
          <BodySectionDescription>
            Raising capital is hard, takes many months to a year, and is not guaranteed. With GoFundYourself, you pitch your idea to make the world a better place and get funded by a network of people who want to support you and your dreams
          </BodySectionDescription>

          <ProjectCardCon>

            <ProjectTimelineCardCon 
              step1={"Make a profile."}
              step2={"Tell everyone what you’re trying to do."}
              step3={"Find a community of people who will help you make it real."}
            />

            <ProjectCard 
              pfp={Will}
              name={"Will"}
              need={"better recording equipment"}
              status={68}
              link={"/123456"}
            />
          
          </ProjectCardCon>

          <div style={{
            textAlign: "center",
            marginTop: "150px",
            display: "flex"
          }}>
            <div style={{
              left: "50%",
              transform: "translateX(-50%)",
              position: "relative",
              display: "flex"
            }}>
              <ProjectCardButton>Launch dream 🚀</ProjectCardButton>
              <ProjectCardButton>Learn more 🤔 </ProjectCardButton>
            </div>
          </div>
          

        </BodySectionCon>

        <BodySectionCon>
          <BodySectionHeader>
           Want to make dreams come true?
          </BodySectionHeader>
          <BodySectionHeader style={{
            fontWeight: "550",
            fontSize: "20pt",
            marginTop: "10px",
            marginBottom: "-20px",
            textDecoration: "none"
          }}>
            Here’s how backers fund change-makers
          </BodySectionHeader>
          <BodySectionDescription>
            YOLO into the blue ocean or pick the best idea for the good of the land.  Be the shit, and reap the harvest!  Bros can have fun funding and finding the true truth, and becoming a network of people to support you too, bro.
          </BodySectionDescription>

          <ProjectCardCon>

            <ProjectTimelineCardCon 
              step1={"Make a profile."}
              step2={"Find a project to support."}
              step3={"Offer your network, advice and finacial backing to a dreamer you want to see win."}
            />

            <InvestorCard 
              pfp={Sergey}
              name={"Sergey"}
              status={12.2}
              link={"/sergey"}
            />
          
          </ProjectCardCon>

          <div style={{
            textAlign: "center",
            marginTop: "150px",
            display: "flex",
          }}>
            <div style={{
              left: "50%",
              transform: "translateX(-50%)",
              position: "relative",
              display: "flex"
            }}>
              <ProjectCardButton>Fund Dreamers 🤑 </ProjectCardButton>
              <ProjectCardButton>Learn more 🤔 </ProjectCardButton>
            </div>
          </div>
        </BodySectionCon>
        

        <BodySectionCon style={{marginTop: "250px"}}>
          <BodySectionHeader>
            See what others are saying:
          </BodySectionHeader>
          <BodySectionDescription>
            You can’t hunt for snarks alone
          </BodySectionDescription>

        

          <div style={{
            textAlign: "center",
            marginTop: "150px",
            display: "flex",
          }}>
            <div style={{
              left: "50%",
              transform: "translateX(-50%)",
              position: "relative",
              display: "flex"
            }}>
              <ProjectCardButton>Fund Dreamers 🤑 </ProjectCardButton>
              <ProjectCardButton>Learn more 🤔 </ProjectCardButton>
            </div>
          </div>
        </BodySectionCon>


        


      </BodyCon>
    </>
  )
  if(isAuthenticated)
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>GoFundYourself</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <h1>Hey you are logged in authenticated!</h1>
    </>
  )
}

export default Home
