import React, {useState} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMoralis } from "react-moralis";

import {
  BodyCon, BodyHeaderCon, RandomizingHeader, SubHeader, PeopleBlobs, HomePageButtonConnectWallet, HomePageButtonConnectWalletInvert, 
  
  ProjectCardCon, ProjectNoFlex, BodySectionCon, BodySectionHeader, BodySectionDescription, ProjectCardButton, TimelineCon,  BodySectionImageCon,

  TestimonialPersonCon, TestimonialPersonImage, TestimonialText, DiveInButton
} from "../components/HomePage/HomePageElements"

import ProjectTimelineCardCon from "../components/Projects/ProjectTimelineCard"
import ProjectCard from "../components/Projects/ProjectCard"
import FeedCard from "../components/Projects/ProjectCard"
import InvestorCard from "../components/Projects/InvestorCard"

import OrangeBlob from "../assets/People/Orange_Blob.png"
import BlueBlob from "../assets/People/Blue_Blob.png"
import PurpleBlob from "../assets/People/Purple_Blob.png"
import DreamerImage from "../assets/SiteElements/dreamerslide.png"
import Will from "../assets/People/memoji-will.png"
import Sergey from "../assets/People/memoji-sergey.png"
import Ahkmaral from "../assets/People/memoji-Ahkmaral.png"
import Pat from "../assets/People/memoji-pat.png"
import projects from "../components/Projects/Projects.json"



/////////////////////////////////// COMPONENT ////////////////////////////////////////////////////////////////






import TextField from "@mui/material/TextField";
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import FormGroup from '@mui/material/FormGroup';
import Card from '@mui/material/Card';
import { styled } from '@mui/material/styles';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';
import DiscordLogo from "../assets/Logos/discord.png"



const StyledTextField = styled(TextField)`
    root: {
      "& fieldset": {
        borderTopRightRadius: 0,
        borderBottomRightRadius: 0
      }
    }
    `;


  const StyledButton = styled(Button)`
    root: {
      display: 'flex',
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      textTransform: "lowercase"
    }
  `;

  const StyledButton2 = styled(Button)`
  root: {
    
    display: 'flex',
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    textTransform: "lowercase"
  }
`;

///////////////////////////////////////////////////////////////////////////


const wordArray = [
  'NFT project', 'Hackathon scholarship', 'Trip to ETHDenver', 'recording equipment', 'Guitar lessons', 'Word bank', 'economic justice', 'literacy program', 'Animation', 'Dream journal', 'Dream vaction', 'Dream job', 'Dream life', 'Data pipeline', 'Production guild bounty', 'Medical bills', 'School', 'College Tuition', 'Language lessons'
]

function Home () {
  const { 
    authenticate, 
    isAuthenticated, 
    user,
  } = useMoralis();

  const [randomItem, setRandomItem] = useState('');

  const [items, setItems] = useState(projects);

  const timoutId = setTimeout(() => {
    var randomItem = wordArray[Math.floor(Math.random() * wordArray.length)];
    setRandomItem(randomItem);
  }, 8000);

  if(!isAuthenticated)
  return (
    <>

        <div> NOT AUTHENTICATED </div>
        <div> NOT AUTHENTICATED </div>
        <div> NOT AUTHENTICATED </div>
        <div> NOT AUTHENTICATED </div>
    </>
  )
  if(isAuthenticated)
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>GoFundYourself</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <BodyCon>

      <ProjectNoFlex style={{float: "center"}}>

      <Box sx={{ display: 'flex', alignItems: 'center', width: "100%" }}>
        <Box sx={{ width: '100%', mr: 1 }}>
          <h2> Let get your page setup!</h2>
            <FormGroup row>
                <StyledTextField id="outlined-basic" label="Projects" variant="outlined" />
                <Button variant="contained">Contained</Button>
            </FormGroup>
        </Box>

    
        <Card >

    
      <CardActionArea>
        <CardMedia
          component="img"
          height="140"
          width="400"
        //   image="https://www.logolynx.com/images/logolynx/99/9960052cf2f5d09d075ab2c1fec5f2ea.jpeg"
          alt="Project 1"
          />
        <CardContent>
          <Typography gutterBottom variant="h5" component="div">
            Project 1
          </Typography>
          <Typography variant="body2" color="text.secondary">
           This is my Project
          </Typography>
        </CardContent>
      </CardActionArea>
      <StyledButton2 sx={{ width: '100%'}} variant="contained" color="primary" size="medium"> Fund This </StyledButton2>
    </Card>
          </Box>



        

    </ProjectNoFlex>

      {/* <h1>Hey you are logged in!</h1>
      {projects.map((item, index) => (
        <FeedCard 
          key={index}
          pfp={Will}
          name={"Will"}
          need={"better recording equipment"}
          status={68}
          link={"/123456"}
        />
        // <div key={index} style={{height: "300px", width: "500px", border: "3px solid black", borderRadius: "20px", marginBottom: "20px"}}>
        //   <h1>{item.title}</h1>
        //   <h2>{item.name}</h2>
        //   <h3>{item.wallet}</h3>
        //   <p>{item.description}</p>
        // </div>
      ))} */}
      </BodyCon>
    </>
  )
}

export default Home
